allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
patchedDependencies:
  vinext@0.0.50: patches/vinext@0.0.50.patch
